FROM golang:1.24-alpine

# Instalar air para hot reload
RUN wget -O - https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh

# Instalar dependências de desenvolvimento
RUN apk add --no-cache git

# Definir diretório de trabalho
WORKDIR /app

# Copiar go mod e sum
COPY go.mod ./

# Baixar dependências
RUN go mod download

# Copiar código fonte
COPY . .

# Configurar air para hot reload
CMD ["air", "-c", ".air.toml"]