FROM golang:1.24-alpine

# instalar o make
RUN apk add --no-cache make

# Instalar air para hot reload
RUN wget -O - https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh

# instalar migrate (Library para migrações de banco de dados)
RUN apk add --no-cache curl unzip \
    && curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz -o migrate.tar.gz \
    && tar -xzvf migrate.tar.gz -C /usr/local/bin \
    && chmod +x /usr/local/bin/migrate \
    && rm migrate.tar.gz

#instalar o sqlc (Gerador de código SQL)
RUN wget https://github.com/sqlc-dev/sqlc/releases/download/v1.24.0/sqlc_1.24.0_linux_amd64.tar.gz \
    && tar -xzf sqlc_1.24.0_linux_amd64.tar.gz -C /go/bin \
    && chmod +x /go/bin/sqlc

# instalar client POSTGRESQL    
RUN apk add --no-cache postgresql-client make

# Instalar dependências de desenvolvimento
RUN apk add --no-cache git

# Definir diretório de trabalho
WORKDIR /app

# Copiar go mod e sum
COPY go.mod ./

# Baixar dependências
RUN go mod download

# Copiar código fonte
COPY . .

# Configurar air para hot reload
CMD ["air", "-c", ".air.toml"]