// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"database/sql"
)

type CancelInfo struct {
	ID          string       `json:"id"`
	Reason      string       `json:"reason"`
	CancelDate  sql.NullTime `json:"cancel_date"`
	CancelledBy string       `json:"cancelled_by"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	DebtID      string       `json:"debt_id"`
}

type Debt struct {
	ID                   string       `json:"id"`
	Description          string       `json:"description"`
	TotalValue           string       `json:"total_value"`
	DueDate              sql.NullTime `json:"due_date"`
	InstallmentsQuantity int32        `json:"installments_quantity"`
	DebtDate             sql.NullTime `json:"debt_date"`
	Status               string       `json:"status"`
	UserClientID         string       `json:"user_client_id"`
	ProductIds           []string     `json:"product_ids"`
	ServiceIds           []string     `json:"service_ids"`
	FinishedAt           sql.NullTime `json:"finished_at"`
	CreatedAt            sql.NullTime `json:"created_at"`
	UpdatedAt            sql.NullTime `json:"updated_at"`
}

type Installment struct {
	ID            string         `json:"id"`
	Description   string         `json:"description"`
	Value         string         `json:"value"`
	DueDate       sql.NullTime   `json:"due_date"`
	DebDate       sql.NullTime   `json:"deb_date"`
	Status        string         `json:"status"`
	PaymentDate   sql.NullTime   `json:"payment_date"`
	PaymentMethod sql.NullString `json:"payment_method"`
	Number        int32          `json:"number"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	DebtID        string         `json:"debt_id"`
}

type ReversalInfo struct {
	ID                      string       `json:"id"`
	Reason                  string       `json:"reason"`
	ReversalDate            sql.NullTime `json:"reversal_date"`
	ReversedBy              string       `json:"reversed_by"`
	ReversedInstallmentQtd  int32        `json:"reversed_installment_qtd"`
	CancelledInstallmentQtd int32        `json:"cancelled_installment_qtd"`
	CreatedAt               sql.NullTime `json:"created_at"`
	UpdatedAt               sql.NullTime `json:"updated_at"`
}

type SchemaMigration struct {
	Version int64 `json:"version"`
	Dirty   bool  `json:"dirty"`
}
